proc mapimport out=sao_carlos datafile='/home/alansilva0/my_shared_file_links/alansilva0/Estatistica_Espacial/sao_carlos.shp';run;
proc mapimport out=sao_carlos_pt datafile='/home/alansilva0/my_shared_file_links/alansilva0/Estatistica_Espacial/sao_carlos_pt.shp';run;

data a;segment=2;v=2;run;
proc gmap data=a map=sao_carlos(where=(SPRPERIMET>10000)) all;
id segment;
choro v;
run;
quit;
data anno_pontos;length text $2.;set sao_carlos_pt;retain hsys '3' xsys ysys '2' when 'a';
function='label';color='black';size=2;style='special';text='J';output;
function='label';color='black';size=2;style='swissb';text=put(avg_z,$2.);position='2';output;
run;
proc gmap data=a map=sao_carlos(where=(SPRPERIMET>10000)) all;
id segment;
choro v / anno=anno_pontos;
run;
quit;

proc sql noprint;
select min(x) into:minx from sao_carlos (where=(SPRPERIMET>10000));
select min(y) into:miny from sao_carlos (where=(SPRPERIMET>10000));
select max(x) into:maxx from sao_carlos (where=(SPRPERIMET>10000));
select max(y) into:maxy from sao_carlos (where=(SPRPERIMET>10000));
quit;
%put minx=&minx maxx=&maxx miny=&miny maxy=&maxy;

/************ Funcao de Intensidade *************************/
data nums;
do y=&miny to &maxy by 100;
do x=&minx to &maxx by 100;
output;
end;
end;
run;
data anno;set nums;
length function style $10. color $8.;
retain line 1 xsys ysys '2' hsys '3' color 'red';
function='label';text='U';position='5';style='marker';size=1;
run;
proc gmap data=a map=sao_carlos(where=(SPRPERIMET>10000)) all;
id segment;
choro v / anno=anno;
run;
quit;


proc ginside data=nums map=Sao_carlos(where=(SPRPERIMET>10000)) out=nums2 insideonly;
id segment;run;

data anno2;set nums2;
length function style $10. color $8.;
retain line 1 xsys ysys '2' hsys '3' color 'red';
function='label';text='U';position='5';style='marker';size=1.5;
run;

proc gmap data=a map=sao_carlos(where=(SPRPERIMET>10000)) all;
id segment;
choro v / anno=anno2;
run;
quit;

proc iml;
use nums2;
read all var{x y} into POINTS;
use sao_carlos_pt;
read all var{x y} into COORD;
m=nrow(points[,1]);
n=nrow(coord[,1]);
print n m;
d=j(1,3,0);                                                                                                                             
nome={"idi" "idj" "d"};                                                                                                                 
create dist from d[colname=nome];                                                                                                       
do i=1 to m;
	do j=1 to n;
	if abs(coord[,1])<180 then do;
		dif=abs(POINTS[i,1]-COORD[j,1]);
		raio=arcos(-1)/180;                                                                                                              
		if dif=0 then arco=0;
		else
		/* Law of Cosines */  
		arco=arcos(sin(POINTS[i,2]*raio)*sin(COORD[j,2]*raio)+cos(POINTS[i,2]*raio)*cos(COORD[j,2]*raio)*cos(dif*raio));
		d[1]=i;  
		d[2]=j;
		d[3]=arco*6371 /*Earth's Radius = 6371 (aproximately)*/;
		append from d;
	end;
	else do;
		d[1]=i;  
		d[2]=j;
		d[3]=sqrt((POINTS[i,1]-COORD[j,1])**2+(POINTS[i,2]-COORD[j,2])**2);   
		append from d;
	end;
	end;
end;
close dist;
quit;
proc means data=dist min q1 median mean q3 max;var d;run;
proc iml;
use nums2;
read all var{x y} into POINTS;
use sao_carlos_pt;
read all var{x y} into COORD;
m=nrow(points[,1]);
n=nrow(coord[,1]);
print n m;
use dist;
read all into dist;
kernel=j(m,2,0);
tau=1000;
u=nrow(dist);print u;
	do i=1 to m;
	kernel[i,1]=i;
	do jj=(i-1)*n+1 to i*n;
		if dist[jj,3]<tau then
		kernel[i,2]=kernel[i,2]+(3/arcos(-1)*tau**2)*(1-(dist[jj,3]/tau)**2)**2;
		else kernel[i,2]=kernel[i,2]+0;
	end;
	end;
create kernel from kernel[colname={"Ponto" "lambda"}];
append from kernel;
quit;

data nums2;merge nums2 kernel;run;
data anno;set nums2;
length function style $10. color $8.;
retain line 1 xsys ysys '2' hsys '3' color 'red';
function='label';text='U';position='6';style='marker';size=1.5;
run;
proc gmap data=a map=sao_carlos(where=(SPRPERIMET>10000)) all;
id segment;
choro v / anno=anno;
run;
quit;
proc sql noprint;
select count(*) into:n from anno;
select min(lambda) into:min from anno;
select max(lambda) into:max from anno;
quit;
data _null_;
nc=int(1+3.3*log10(&n))-1;
call symput('nc',nc);
run;
%put &nc;
%put &n &min &max %sysevalf((&max-&min)/&nc);
%include '/home/alansilva0/my_shared_file_links/alansilva0/Estatistica_Espacial/colorscaleMACRO.sas';
%colorscale(FFFFFF,,FF0000,&nc,clist,no);%patt;
data _null_;set clist;
call symput('color'||trim(left(_n_)),'cx'||rgb);
run;
%put &color1;
%macro cl;
data anno2;set anno;
if round(lambda,0.01)<=round(&min+(&max-&min)/&nc,0.01) then color="&color1";
%do i=2 %to &nc;
else if round(lambda,0.01)<=&min+round(&i*(&max-&min)/&nc,0.01) then color="&&color&i";
%end;
if lambda=0 then color="white";
run;
%mend cl;
%cl;
proc gmap data=a map=sao_carlos(where=(SPRPERIMET>10000)) all anno=anno_pontos;
id segment;
choro v / anno=anno2;
run;
quit;

proc sql noprint;
select min(x) into:minx from sao_carlos (where=(SPRPERIMET>10000));
select min(y) into:miny from sao_carlos (where=(SPRPERIMET>10000));
select max(x) into:maxx from sao_carlos (where=(SPRPERIMET>10000));
select max(y) into:maxy from sao_carlos (where=(SPRPERIMET>10000));
quit;
%put minx=&minx maxx=&maxx miny=&miny maxy=&maxy;

proc spp data=sao_carlos_pt plots(equate)=(trends observations);
   process AVG_Z = (x, y /area=(&minx,&miny,&maxx,&maxy) Event=AVG_Z) / 
   kernel(type=gaussian b=500 out=kernel grid(90,90));
run;


/************ Metodo do Vizinho mais Proximo *******************/

proc iml;
use sao_carlos_pt;
read all var{x y} into COORD;
n=nrow(coord[,1]);
*print n;
d=j(1,3,0);                                                                                                                             
nome={"idi" "idj" "d"};                                                                                                                 
create dist from d[colname=nome];                                                                                                       
do i=1 to n;
	do j=i+1 to n;
	if abs(coord[,1])<180 then do;
		dif=abs(COORD[i,1]-COORD[j,1]);
		raio=arcos(-1)/180;                                                                                                              
		if dif=0 then arco=0;
		else
		/* Law of Cosines */  
		arco=arcos(sin(COORD[i,2]*raio)*sin(COORD[j,2]*raio)+cos(COORD[i,2]*raio)*cos(COORD[j,2]*raio)*cos(dif*raio));
		d[1]=i;  
		d[2]=j;
		d[3]=arco*6371 /*Earth's Radius = 6371 (aproximately)*/;
		append from d;
	end;
	else do;
		d[1]=i;  
		d[2]=j;
		d[3]=sqrt((COORD[i,1]-COORD[j,1])**2+(COORD[i,2]-COORD[j,2])**2);   
		append from d;
	end;
	end;
end;
close dist;
quit;
proc sql noprint;select max(d) into:maxd from dist;quit;%put &maxd;
proc freq data=dist noprint;
tables idj /out=teste;
where d<400;
run;
proc sql;select count(*) as Total from teste;quit;
proc iml;
use dist;
read all into dist;
call sort(dist,{2,3});
*print dist;
g=j(1,2,0);                                                                                                                             
nome={"h" "freq"};                                                                                                                 
create g from g[colname=nome];                                                                                                       
do h=0 to max(dist[,3]) by 100;
	g[1]=h;
	do j=2 to nrow(dist[,3]);
		if dist[j,3]<h & dist[j,2]^=dist[j-1,2]  then
		g[2]=g[2]+1;
	end;
	append from g;
	g=j(1,2,0);                                                                                                                             
end;
close g;
quit;
proc sql noprint;select count(*) into: nevents from Sao_carlos_pt;quit;%put &nevents;
data g;set g;
g=freq/&nevents;
run;
goption reset=all reset=global;
proc gplot data=g;
plot g*h /vaxis=axis1;
symbol i=join;
axis1 label=(a=90 "G(h)");
run;
quit;

proc sql noprint;
select min(x) into:minx from sao_carlos (where=(SPRPERIMET>10000));
select min(y) into:miny from sao_carlos (where=(SPRPERIMET>10000));
select max(x) into:maxx from sao_carlos (where=(SPRPERIMET>10000));
select max(y) into:maxy from sao_carlos (where=(SPRPERIMET>10000));
quit;
%put minx=&minx maxx=&maxx miny=&miny maxy=&maxy;

proc spp data=sao_carlos_pt edgecorr=on seed=1 plots(equate)=(observations K);
   process AVG_Z = (x, y /event=fid) / K G L quadrat;
run;


/*********** Envelope de Simulacao ****************************/

%macro csr(data);
proc iml;
use &data;
read all var{x y} into COORD;
n=nrow(coord[,1]);
*print n;
d=j(1,3,0);                                                                                                                             
nome={"idi" "idj" "d"};                                                                                                                 
create dist from d[colname=nome];                                                                                                       
do i=1 to n;
	do j=i+1 to n;
	if abs(coord[,1])<180 then do;
		dif=abs(COORD[i,1]-COORD[j,1]);
		raio=arcos(-1)/180;                                                                                                              
		if dif=0 then arco=0;
		else
		/* Law of Cosines */  
		arco=arcos(sin(COORD[i,2]*raio)*sin(COORD[j,2]*raio)+cos(COORD[i,2]*raio)*cos(COORD[j,2]*raio)*cos(dif*raio));
		d[1]=i;  
		d[2]=j;
		d[3]=arco*6371 /*Earth's Radius = 6371 (aproximately)*/;
		append from d;
	end;
	else do;
		d[1]=i;  
		d[2]=j;
		d[3]=sqrt((COORD[i,1]-COORD[j,1])**2+(COORD[i,2]-COORD[j,2])**2);   
		append from d;
	end;
	end;
end;
close dist;
quit;
proc iml;
use dist;
read all into dist;
call sort(dist,{2,3});
*print dist;
g=j(1,2,0);                                                                                                                             
nome={"h" "freq"};                                                                                                                 
create g from g[colname=nome];                                                                                                       
do h=0 to &maxd by 100;
	g[1]=h;
	do j=2 to nrow(dist[,3]);
		if dist[j,3]<h & dist[j,2]^=dist[j-1,2]  then
		g[2]=g[2]+1;
	end;
	append from g;
	g=j(1,2,0);                                                                                                                             
end;
close g;
quit;
%mend csr;

%macro envelope;
%do i=1 %to 100;
proc surveyselect data=Sao_carlos_pt out=amostra method=srs sampsize=30
noprint seed=&i;run;
%csr(amostra);
data g;set g;g=freq/30;simulacao=&i;run;
proc append base=envelope data=g force;run;
%end;
%mend envelope;
%envelope;
proc means data=envelope noprint;
var g;
class h;
output out=envelope2(where=(_type_=1)) mean=g_simulada min=l_simulada max=u_simulada;
run;

proc sql noprint;select count(*) into: nevents from Sao_carlos_pt;quit;%put &nevents;
%csr(Sao_carlos_pt);
data g;set g;
g=freq/&nevents;
run;
data g;merge g envelope2;run;
proc gplot data=g;
plot g*g_simulada g*l_simulada g*u_simulada g*g  / overlay vaxis=axis1;
symbol1 i=join c=black;
symbol2 i=join c=green l=2;
symbol3 i=join c=green l=2;
symbol4 i=join c=red;
axis1 label=(a=90 "G(h) Estimados");
axis2 label=("G(h) Simulados");
run;
quit;

data sao_carlos1;set sao_carlos(where=(SPRPERIMET>10000));run;
proc iml;
use sao_carlos1;
read all var{x y} into p;
areapoligono=0;
n=nrow(p);
do i=1 to n;
i1=mod(i+1,n);
if i1 ^=0 then areapoligono=areapoligono+(p[i,2]+p[i1,2])*(p[i1,1]-p[i,1])/2;
end;
print areapoligono;
lambda=&nevents/areapoligono;
create lambda from lambda[colname={"lambda"}];
append from lambda;
quit;
data _null_;set lambda;call symput('lambda',lambda);run;%put &lambda;
data csr;
do h=0 to &maxd by 100;
gcsr=1-exp(-&lambda*arcos(-1)*h**2);
output;
end;
run;
proc gplot data=csr;
plot gcsr*h /vaxis=axis1;
symbol i=join;
axis1 label=(a=90 "G(h)");
run;
quit;

/************************* funcao k ***************************/

data _null_;set Sao_carlos_pt;
call symput('x'||trim(left(_n_)),x);
call symput('y'||trim(left(_n_)),y);
call symput('AVG_Z'||trim(left(_n_)),trim(left(AVG_Z)));
run;
%put &x1 &y1;
proc iml;
use sao_carlos_pt;
read all var{x y} into COORD;
n=nrow(coord[,1]);
*print n;
d=j(1,3,0);                                                                                                                             
nome={"idi" "idj" "d"};                                                                                                                 
create dist from d[colname=nome];                                                                                                       
do i=1 to n;
	do j=i+1 to n;
	if abs(coord[,1])<180 then do;
		dif=abs(COORD[i,1]-COORD[j,1]);
		raio=arcos(-1)/180;                                                                                                              
		if dif=0 then arco=0;
		else
		/* Law of Cosines */  
		arco=arcos(sin(COORD[i,2]*raio)*sin(COORD[j,2]*raio)+cos(COORD[i,2]*raio)*cos(COORD[j,2]*raio)*cos(dif*raio));
		d[1]=i;  
		d[2]=j;
		d[3]=arco*6371 /*Earth's Radius = 6371 (aproximately)*/;
		append from d;
	end;
	else do;
		d[1]=i;  
		d[2]=j;
		d[3]=sqrt((COORD[i,1]-COORD[j,1])**2+(COORD[i,2]-COORD[j,2])**2);   
		append from d;
	end;
	end;
end;
close dist;
quit;

data _null_;set Sao_carlos_pt;
call symput('x'||trim(left(_n_)),x);
call symput('y'||trim(left(_n_)),y);
call symput('AVG_Z'||trim(left(_n_)),trim(left(AVG_Z)));
run;
%put &x1 &y1;
data _null_;set dist;
call symput('d'||trim(left(idi))||trim(left(idj)),d);
run;
%put &d12;
proc sql noprint;select count(*) into: nevents from Sao_carlos_pt;quit;%put &nevents;


%let i=2;
data circulo;
id=1;
do x=&x1-&&d1&i to &x1+&&d1&i by 100;
z=&&d1&i**2-(x-&x1)**2;
if z<=0 then y=&y1;else y=sqrt(&&d1&i**2-(x-&x1)**2)+&y1;
output;
end;
run;
data circulo2;
id=1;
do x=&x1+&&d1&i to &x1-&&d1&i by -100;
z=&&d1&i**2-(x-&x1)**2;
if z<=0 then y=&y1;else y=-sqrt(&&d1&i**2-(x-&x1)**2)+&y1;
output;
end;
run;
data circulo;set circulo circulo2;run;
proc sql noprint;
select min(x) into:minx from circulo;
select min(y) into:miny from circulo;
select max(x) into:maxx from circulo;
select max(y) into:maxy from circulo;
quit;
%put minx=&minx maxx=&maxx miny=&miny maxy=&maxy;
data nums;
do y=&miny to &maxy by 50;
do x=&minx to &maxx by 50;
output;
end;
end;
run;
proc ginside data=nums map=circulo out=dentro_circulo insideonly;id id;run;
proc ginside data=dentro_circulo map=Sao_carlos(where=(SPRPERIMET>10000)) out=dentro_poligono insideonly;id segment;run;
data anno;length text $2.;set dentro_circulo;retain hsys '3' xsys ysys '2' when 'a';
function='label';text='U';position='6';style='marker';size=2;color="red";
run;
proc gmap data=a map=circulo(rename=id=segment) all;
id segment;
choro v / anno=anno nolegend;
run;quit;
data anno;length text $2.;set dentro_poligono;retain hsys '3' xsys ysys '2' when 'a';
function='label';text='U';position='6';style='marker';size=2;color="red";
run;
proc gmap data=a map=Sao_carlos(where=(SPRPERIMET>10000)) all;
id segment;
choro v / anno=anno nolegend;
run;quit;
proc sql noprint;
select count(*) into: total from dentro_circulo;
select count(*) into: dentro from dentro_poligono;
quit;
%put "Percentual = &dentro/&total = " %sysevalf(&dentro/&total);


%macro circ;
proc sql;create table area (idi num, idj num, pct num);quit;
%do i=1 %to &nevents;
%do j=&i+1 %to &nevents;
data circulo;
id=1;
do x=&&x&i-&&&d&i&j to &&x&i+&&&d&i&j by 500;
z=&&&d&i&j**2-(x-&&x&i)**2;
if z<=0 then y=&&y&i;else y=sqrt(&&&d&i&j**2-(x-&&x&i)**2)+&&y&i;
output;
end;
run;
data circulo2;
id=1;
do x=&&x&i+&&&d&i&j to &&x&i-&&&d&i&j by -500;
z=&&&d&i&j**2-(x-&&x&i)**2;
if z<=0 then y=&&y&i;else y=-sqrt(&&&d&i&j**2-(x-&&x&i)**2)+&&y&i;
output;
end;
run;
data circulo;set circulo circulo2;run;
proc sql noprint;
select min(x) into:minx from circulo;
select min(y) into:miny from circulo;
select max(x) into:maxx from circulo;
select max(y) into:maxy from circulo;
quit;
%put minx=&minx maxx=&maxx miny=&miny maxy=&maxy;
data nums;
do y=&miny to &maxy by 500;
do x=&minx to &maxx by 500;
output;
end;
end;
run;
proc ginside data=nums map=circulo out=dentro_circulo insideonly;id id;run;
proc ginside data=dentro_circulo map=Sao_carlos(where=(SPRPERIMET>10000)) out=dentro_poligono insideonly;id segment;run;
proc sql noprint;
select count(*) into: total from dentro_circulo;
select count(*) into: dentro from dentro_poligono;
quit;
proc sql;insert into area values (&i, &j, %sysevalf(&dentro/&total));quit;
%end;
%end;
%mend circ;
%circ; 

data sao_carlos1;set sao_carlos(where=(SPRPERIMET>10000));run;
proc iml;
use sao_carlos1;
read all var{x y} into p;
areapoligono=0;
n=nrow(p);
do i=1 to n;
i1=mod(i+1,n);
if i1 ^=0 then areapoligono=areapoligono+(p[i,2]+p[i1,2])*(p[i1,1]-p[i,1])/2;
end;
print areapoligono;
use dist;
read all into dist;
use area;
read all into area;
contador=0;
l=j(1,3,0);                                                                                                                             
nome={"h" "freq" "area"};                                                                                                                 
create L from l[colname=nome];   
do h=0 to max(dist[,3]) by 100;
	l[1]=h;
	l[3]=areapoligono;
	do j=1 to nrow(dist[,3]);
		if dist[j,3]<=h then l[2]=l[2]+1/area[j,3];
	end;
	append from l;
	l=j(1,3,0);
end; 
close l;
quit;
data l;set l;lh=sqrt((freq*area/&nevents**2)/arcos(-1))-h;run;
proc gplot data=l;
plot lh*h /vaxis=axis1;
symbol i=join;
axis1 label=(a=90 "L(h)");
run;
quit;




/************** verificando o tamanho dos circulos *********************/

data _null_;set Sao_carlos_pt;
call symput('x'||trim(left(_n_)),x);
call symput('y'||trim(left(_n_)),y);
call symput('AVG_Z'||trim(left(_n_)),trim(left(AVG_Z)));
run;
%put &x1 &y1;
data _null_;set dist;
call symput('d'||trim(left(idi))||trim(left(idj)),d);
run;
%put &d12;
%macro raio;
proc sql noprint;select count(*) into:n from Sao_carlos_pt;quit;
%do i=2 %to 85;
data circulo;
id=1;
do x=&x1-&&d1&i to &x1+&&d1&i by 100;
if x>=&x1+&&d1&i then y=&y1;else y=sqrt(&&d1&i**2-(x-&x1)**2)+&y1;
output;
end;
run;
data circulo2;
id=1;
do x=&x1+&&d1&i to &x1-&&d1&i by -100;
if x>=&x1+&&d1&i then y=&y1;else y=-sqrt(&&d1&i**2-(x-&x1)**2)+&y1;
output;
end;
run;
data circulo;set circulo circulo2;run;
data a;id=99;v=2;run;
/*proc gmap data=a map=circulo all;
id id;
choro v /nolegend;
run;
quit;*/

data circulo;set circulo;x1=lag1(x);y1=lag1(y);if x1=. then delete;run;
proc sql noprint;select count(*) into:max from circulo;quit;%put &max;
data circulo_1;set circulo;if _n_=&max;x1=x;y1=y;run;
data circulo_2;set circulo;if _n_=1;x1=x;y1=y;run;
data circulo_2;merge circulo_2 circulo_1(drop=x1 y1);run;
data circulo;set circulo circulo_2;run;
data anno1;length function style color $8 position $1 text $20;retain xsys ysys '2' hsys '3' when 'a';
set circulo;
style='music';text='A';color='orange';size=0.2;position='5';line=1;
function='move';x=x;y=y;output;
function='draw';x=x1;y=y1;output;
run;
data a;segment=2;v=2;run;
data anno_pontos1;set anno_pontos;if FID=1 or FID=&i then color='red';run;
title "Ponto &AVG_Z1 ate Ponto &&AVG_Z&i";
proc gmap data=a map=sao_carlos(where=(SPRPERIMET>10000)) anno=anno_pontos1 all;
id segment;
choro v / anno=anno1;
run;
quit;
%end;
%mend raio;
%raio;


